### ISSUE TITLE
parameters setup

### ISSUE THREAD

**Issue by cszmli** [truthless11/GDPL#1]
Hi, thanks for sharing the code. Do I need to change the parameters to get the same results in the paper? I got the following results with the default parameters (the epoch number was set to 500 during policy training while it was 32 during pretraining). It looks like the success rate is 0 during testing. 
<img width="1155" alt="Screenshot 2019-09-06 at 09 59 43" src="https://user-images.githubusercontent.com/18543171/64411283-2585c280-d08d-11e9-8ae9-93843228033d.png">

**Comment by truthless11** [comment]
@cszmli  Thanks for reporting the issue. I have updated the code and README. Now you can get the results in the EMNLP paper by using the updated parameters.

**Comment by cszmli** [comment]
Hi, I rerun the experimental setup based on the parameters you updated but only got 0.566 with respect to the success rate. I increased the training epoch to 200 and the success rate was still below 0.7. Much appreciate if you can go through the setup again.
<img width="747" alt="Screenshot 2019-09-27 at 09 12 36" src="https://user-images.githubusercontent.com/18543171/65749728-fbad4200-e106-11e9-82ab-0905563a9f3d.png">
