### ISSUE TITLE
About ACER and PPO

### ISSUE THREAD

**Issue by shuyulei0130** [truthless11/GDPL#4]
Dear,
Thank you for proposing an impressive work. Could you release the code about ACER and pure PPO in “Guided Dialog Policy Learning: Reward Estimation for Multi-Domain Task-Oriented Dialog”?

**Comment by truthless11** [comment]
Thanks for your interest in work GPDL, but sorry that I haven't saved the code of ACER and PPO. The policy of GDPL is based on PPO, and you can refer to the `task_complete` function in `agenda.py` to use a handcrafted reward function.

**Comment by shuyulei0130** [comment]
> Thanks for your interest in work GPDL, but sorry that I haven't saved the code of ACER and PPO. The policy of GDPL is based on PPO, and you can refer to the `task_complete` function in `agenda.py` to use a handcrafted reward function.

OK, thank you
