### ISSUE TITLE
Process parameter

### ISSUE THREAD

**Issue by zhenduow** [truthless11/GDPL#6]
Hi Ryuichi,

Because I always get CUDA OOM error using the default parameters, I changed the `--process` from 16 to 8 and use all the other hyperparameters you suggested in another thread. But then I can't get the same result as in the other thread. I run the code in the following steps:

```
python main.py --pretrain True --save_dir model_agenda --process 8
python main.py --load model_agenda/best --lr_rl 1e-4 --lr_irl 1e-4 --epoch 16 --process 8 
python main.py --test True --load model_agenda/best > result.txt
```

This is what I get:

```
INFO:root:reward 1.5343835609768526
INFO:root:turn 13.591
INFO:root:match 0.5826771653543307
INFO:root:inform rec 0.674292250500429, F1 0.7755303404045387
INFO:root:success 0.546
```

Is that because that I turn down the `process`? Do you have a chance to test it using `--process 8`, and what do you get? Just want to double check it with you. Thank you very much!

Best,

**Comment by truthless11** [comment]
Try to turn down the `epoch` during AIRL training

**Comment by zhenduow** [comment]
Hi,

I tried to run the training for 1, 4, 8, 16, 32 and 100 epochs, but all of them give me final success below 0.6. Did you happen to get any success runs using `--process 8`? 

Thank you!

Best,
