### ISSUE TITLE
No such file or directory: 'data/restaurant_db.json'

### ISSUE THREAD

**Issue by shiranD** [truthless11/GDPL#7]
Thank you for working on this and releasing the algorithm!

After fetching the data, I get an xml like file. I renamed is to restaurant_db.json and tried running the pretraining cmd, then it failed with this comment. 
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

No place renaming was mentioned, but I didn't have the restaurant_db.json and that's why I did it.
I assume I am missing something and there should be a very simple way to sort it out.
Thanks again,
Shiran

**Comment by truthless11** [comment]
@shiranD Try download from https://drive.google.com/file/d/18TYwvoA1viGtOPbj-15KlGJYxXOjnhrr directly, and unzip it under the `data` directory.
